/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package secretsanta;
import java.util.HashMap;
import java.util.ArrayList;
import java.util.Random;

public class secretSanta {
    ArrayList<String> buyer = new ArrayList<String>();
    ArrayList<String> seller = new ArrayList<String>();
    Random rand = new Random();

    public void main(String[] args) {
        buildArrays();
        assignNames();
    }

    public void buildArrays() {
        buyer.add("Anne");
        buyer.add("Ben");
        buyer.add("Emma");
        buyer.add("Ian");
        buyer.add("Kelvin");
        buyer.add("Laura");
        seller.add("Anne");
        seller.add("Ben");
        seller.add("Emma");
        seller.add("Ian");
        seller.add("Kelvin");
        seller.add("Laura");
    }

    public void assignNames() {
        HashMap<String, String> assignments = new HashMap<String, String>();
        for (int b = 0; b < buyer.size(); b++) {
            int s = rand.nextInt(5);
            s += 1;
            assignments.put(buyer.get(b), seller.get(s));
            buyer.remove(b);
            seller.remove(s);
        }
        System.out.println(assignments);
    }

}
